[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/run/singdock/supervisord.pid
childlogdir=/run/singdock

[unix_http_server]
file=/run/singdock/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/singdock/supervisor.sock

[program:sing-box]
command=/usr/local/bin/sing-box run -c /opt/sing-box/config.json -D /opt/sing-box/data
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:warp-svc]
command=/usr/bin/warp-svc
autostart=false
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:gui]
command=/opt/singdock/venv/bin/python /opt/singdock/web/server.py
autostart=false
autorestart=true
startsecs=2
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
